### ISSUE TITLE
 java.lang.NoSuchMethodError: No static method encodeHexString([B)Ljava/lang/String; in class 

### ISSUE THREAD

**Issue by suwu150** [qcloudsms/qcloudsms_java#18]
```
D/List: [interfaces.heweather.com.interfacesmodule.bean.weather.now.Now@6f4bf1e]
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jkwu.wsforever, PID: 14562
    java.lang.NoSuchMethodError: No static method encodeHexString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)
        at org.apache.commons.codec.digest.DigestUtils.sha256Hex(DigestUtils.java:623)
        at com.github.qcloudsms.SmsSenderUtil.sha256(SmsSenderUtil.java:117)
        at com.github.qcloudsms.SmsSenderUtil.calculateSignature(SmsSenderUtil.java:38)
        at com.github.qcloudsms.SmsSingleSender.send(SmsSingleSender.java:57)
        at com.jkwu.wsforever.activity.SendWeatherSMS$1.onClick(SendWeatherSMS.java:53)
        at android.view.View.performClick(View.java:6367)
        at android.view.View$PerformClick.run(View.java:25032)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
W/OPDiagnose: getService:OPDiagnoseService NULL
D/OSTracker: OS Event: crash
```

**Comment by qcloudsms** [comment]
您好，qcloudsms_java用于server端发送短信，不支持直接在android端发短信

**Comment by lalaphoon** [comment]
you can try `new String(Hex.encodeHex(xxx));`

**Comment by Aheadboy** [comment]
> you can try `new String(Hex.encodeHex(xxx));`

This is work for me.Thank you

**Comment by Aheadboy** [comment]
> you can try `new String(Hex.encodeHex(xxx));`

这个可以用，谢谢。

**Comment by morarafrank** [comment]
It encodes and produces a different encoded string with an equal sign in the end. not the same
